### ISSUE TITLE
글자모양 의 글자안 버튼의 설정이 반영안됨

### ISSUE THREAD

**Issue by molddu** [molddu/wordinart.github.io#10]
글자모양 메뉴에서 의 글자안 버튼의 설정이 반영안됨
그래서, 두개다 글자 밖에 찍는 결과가 나옴

**Comment by zapha** [comment]
@molddu 이거는 Invert "F"로 보내는거 같은데 나중에 회의 해보죠

**Comment by molddu** [comment]
서버로그 보니 클라이언트에서는 정상적으로 파라미터 보냄.
서버쪽에서 해당 파라미터 반영을 안하고 있었음.
서버 업데이트 완료

**Comment by molddu** [comment]
서버로그 보니 클라이언트에서는 정상적으로 파라미터 보냄.
서버쪽에서 해당 파라미터 반영을 안하고 있었음.
서버 업데이트 완료
