### ISSUE TITLE
영어앱 폰트 추가

### ISSUE THREAD

**Issue by molddu** [molddu/wordinart.github.io#19]
음영이나 돋보이는 모양의 폰트들 추가 (먼저 윗부분에 노출되도록 추가)

 'VastShadow-Regular': 'vastshadow/VastShadow-Regular.ttf',
 'LondrinaShadow-Regular': 'londrinashadow/LondrinaShadow-Regular.ttf',
 'JacquesFrancoisShadow-Regular': 'jacquesfrancoisshadow/JacquesFrancoisShadow-Regular.ttf',
 'EmilysCandy-Regular': 'emilyscandy/EmilysCandy-Regular.ttf',
 'RalewayDots-Regular': 'ralewaydots/RalewayDots-Regular.ttf',
 'TrainOne-Regular': 'trainone/TrainOne-Regular.ttf',
 'UnifrakturMaguntia': 'unifrakturmaguntia/UnifrakturMaguntia-Book.ttf',
 'Frijole': 'frijole/Frijole-Regular.ttf',
 'BungeeInline-Regular': 'bungeeinline/BungeeInline-Regular.ttf',
 'Rye-Regular': 'rye/Rye-Regular.ttf',
 'CabinSketch-Regular': 'cabinsketch/CabinSketch-Regular.ttf',
 'BigShouldersInlineText-Thin': 'bigshouldersinlinetext/BigShouldersInlineText-Thin.ttf',
 'BigShouldersStencilText-Thin': 'bigshouldersstenciltext/BigShouldersStencilText-Thin.ttf',
 'Nosifer-Regular': 'nosifer/Nosifer-Regular.ttf',
 'MysteryQuest': 'mysteryquest/MysteryQuest-Regular.ttf',
 'ZillaSlabHighlight-Regular': 'zillaslabhighlight/ZillaSlabHighlight-Regular.ttf',
 'Akronim-Regular': 'akronim/Akronim-Regular.ttf',
 'RibeyeMarrow-Regular': 'ribeyemarrow/RibeyeMarrow-Regular.ttf',
 'Monofett': 'monofett/Monofett.ttf',
 'CaesarDressing-Regular': 'caesardressing/CaesarDressing-Regular.ttf',
 'DiplomataSC-Regular': 'diplomatasc/DiplomataSC-Regular.ttf',
 'SirinStencil-Regular': 'sirinstencil/SirinStencil-Regular.ttf',
 'FascinateInline-Regular': 'fascinateinline/FascinateInline-Regular.ttf',
 'Hanalei-Regular': 'hanalei/Hanalei-Regular.ttf',

**Comment by zapha** [comment]
적용 완료
