### ISSUE TITLE
글자모양을 입력할때의 글자가 너무 작게 나오는 현상

### ISSUE THREAD

**Issue by molddu** [molddu/wordinart.github.io#21]
글자모양을 입력할때의 글자가 너무 작게 나오는 현상
세로 길이가 짧은 폰에서 글자모양 기능 입력시에 발생...

![Capture+_2021-05-12-18-25-56](https://user-images.githubusercontent.com/4981259/117943885-f0487200-b34f-11eb-8d5e-5f96b8408ade.png)

**Comment by zapha** [comment]
고정 사이즈로 픽스하기로 결정
