### ISSUE TITLE
앱 테스트 논의 사항

### ISSUE THREAD

**Issue by molddu** [molddu/wordinart.github.io#28]
- [x]  "Word in background" ==> "Word Art in background"
- [x]  "Word in background"에 있는 스위치를 켜고 끌때에 왼쪽 이미지만 바뀌는 데, 의미 전달이 부족한 것 같음 -> 네모 모양으로 교체
- [x]  "Font" ==> "Shape font"
- [x]  텍스트 입력할 때에 밑줄 안나오게 되나
- [x]  탭뷰이지만 위에 탭을 눌렀을 경우에면 다른 탭으로 이동하게 하는 것
- [x]  각 서브 제목과 내용이 구분이 잘 안되는 문제
- [x]  이모지 쉐이프나 텍스트 쉐이프 중 최근에 사용한 것으로 유지 안되고, 항상 이모지 쉐이프 탭이 먼저 보이는 것
- [x] 메인 화면에 shape icon 네모 모양으로
- [x] 이모지 선택시 바로 메인화면이 아닌 선택됨으로 표시
- [x]  Keywords에 0/30은 각 키워드의 글자수가 아닌 키워들 들의 개수를 세어야함

**Comment by zapha** [comment]
Text shape font => Shape font

**Comment by zapha** [comment]
텍스트 입력할 때에 밑줄은 안드로이드 오토 correct feature 임. 다른 해결 방법으로는 그냥 다른 텍스트 필드처럼 작게 가는것. 논의 필요.
